Add meta theme-color
astrobin/astrobin pull request #1542
Opened 2020-10-29 21:07 UTC by HunterHarling

Added a theme-color of #303030 for mobile

2020-10-29 21:21 UTC, siovene requested changes

2020-10-29 21:21 UTC, siovene commented on astrobin/templates/base/meta.html
> +<meta name="theme-color" content="#303030" />
Can you please do this also for the other base pages? 

- [ ] `image/full.html`
- [ ] `mainenance_base.html`
- [ ] `error_base.html`

Thanks!

2020-10-29 22:35 UTC, HunterHarling commented on astrobin/templates/base/meta.html
> +<meta name="theme-color" content="#303030" />
Yes, I had missed those. I added it to them now also.

2020-10-30 07:24 UTC, siovene commented
Hi @HunterHarling , what am I supposed to see? Looks the same as without this, on my phone (Chrome for Android, Galaxy S10):

![Screenshot_20201030-082211_Chrome](https://user-images.githubusercontent.com/891580/97671812-3cedef00-1a89-11eb-9ec1-1c5bd9be3e94.jpg)
![Screenshot_20201030-082222_Chrome](https://user-images.githubusercontent.com/891580/97671821-411a0c80-1a89-11eb-9a80-1884149beeb9.jpg)

2020-10-30 08:42 UTC, HunterHarling commented
That's interesting, it looks like your phone has a default gray color for the Chrome header. On my phone, the header is white by default, and different theme-colors change the header and top info bar to different colors.
Here is with theme-color of #303030 and then one of #CC4B2E:
![Screenshot_20201030-013807](https://user-images.githubusercontent.com/52986232/97678355-ebc20900-1a50-11eb-9852-93691f911dce.png)
![Screenshot_20201030-013819](https://user-images.githubusercontent.com/52986232/97678397-faa8bb80-1a50-11eb-88f6-f588491c0c7b.png)

2020-10-30 16:23 UTC, merged

2020-10-30 16:27 UTC, siovene commented
@HunterHarling would you have time to do the same also for the Angular app?