Re-center top picks and fix unnecessary margin
astrobin/astrobin pull request #1575
Opened 2020-11-05 08:30 UTC by HunterHarling

Closes #1549

2020-11-06 20:00 UTC, siovene requested changes
Sweet, thanks! I love `display: flex`, so modern :) Can you do the same for the new "top pick nominations" page?

2020-11-07 22:31 UTC, HunterHarling commented
Yes, I hadn't noticed the nominations page, I will add it there also.

2020-11-13 21:35 UTC, siovene commented
Hi @HunterHarling, thanks for doing it for the IOTD _submission_ queues, but you missed my point: I meant the _top pick nominations_ list:

`astrobin/templates/top_pick_nominations.html`

😇

2020-11-14 08:59 UTC, HunterHarling commented
Ah, the nominations page ;) I can do it there as well. The submission queue needed it as well, so I'm glad I added it there though.

2020-11-16 03:22 UTC, HunterHarling commented
Added to nominations page :)

2020-11-19 07:10 UTC, siovene requested changes

2020-11-19 07:10 UTC, siovene commented on astrobin/static/astrobin/scss/astrobin.scss
> +  justify-content: center;
Sorry, one more thing. Can you make this (and the other one) `flex-start` for screen resolutions where they are supposed to display 2 in a row and `center` only for smaller displays where they only fit one per row?

This happens otherwise:

<img width="1015" alt="Screen Shot 2020-11-19 at 7 56 37" src="https://user-images.githubusercontent.com/891580/99633128-b3ee2600-2a3e-11eb-8eae-0f931f5e2864.png">

2020-11-19 08:10 UTC, HunterHarling commented on astrobin/static/astrobin/scss/astrobin.scss
> +  justify-content: center;
Okay, I added `justify-content: space-between` for larger screens. I also removed the placeholder from the templates since there are only two items and it was contributing to the issue.

2020-11-19 18:31 UTC, merged

2020-11-19 18:31 UTC, siovene commented
@HunterHarling awesome, thanks a lot!