Add tests for image likes and comments
astrobin/astrobin pull request #1844
Opened 2021-01-17 22:21 UTC by HunterHarling

2021-01-18 08:39 UTC, siovene requested changes
Hi @HunterHarling, thanks for the PR! Are these tests green locally for you? `image.js` is failing on CI.

2021-01-18 08:39 UTC, siovene commented on cypress/integration/image.js
> +        cy.likeImage();
Hi @HunterHarling, thanks for the PR!

The point of Cypress commands is to have reusable bits, not simply be wrapped in tests. Now I agree that `likeImage` could be reusable, but the `likeImage` also unlikes it, so it's not really a reusable command to like an image.

2021-01-18 08:39 UTC, siovene commented on cypress/support/commands/image.js
> +    cy.visitImage();
Please remove the `visitImage` command and do the page orchestration in the test instead, making the command better reusable.

2021-01-18 08:39 UTC, siovene commented on cypress/support/commands/image.js
> +    cy.visitImage();
Same here.

2021-01-18 08:39 UTC, siovene commented on cypress/support/commands/image.js
> +    cy.visitImage();
Same here.

2021-01-18 08:43 UTC, HunterHarling commented on cypress/support/commands/image.js
> +    cy.visitImage();
Sure thing! That makes sense. 

Also, I originally included tests for editing and deleting comments but the new comment moderation requires that they be moderated first before, so I decided to remove them at least for now.

2021-01-19 21:03 UTC, siovene requested changes

2021-01-19 21:03 UTC, siovene commented on cypress/support/commands/image.js
> +        btn.should("contain", "Unlike");
Now you double-login because you also login at cypress/integration/image.js line 4. Can you remove this and just assume that the user of this command takes care of logging in?

2021-01-19 21:03 UTC, siovene commented on cypress/support/commands/image.js
> +        btn.should("contain", "Like");
Same here.

2021-01-19 21:03 UTC, siovene commented on cypress/support/commands/image.js
> +    cy.get(".uncollapse").click();
Can you make this and the following lines more specific? If necessary, please add classes where needed.

2021-01-19 22:10 UTC, HunterHarling commented on cypress/support/commands/image.js
> +    cy.get(".uncollapse").click();
I added some classes, hopefully, they are more descriptive now.

2021-01-24 07:53 UTC, siovene approved these changes
Thank you @HunterHarling!

2021-01-24 07:54 UTC, merged