add ui-multiselect-zh-CN.js
astrobin/astrobin pull request #1992
Opened 2021-03-04 10:32 UTC by aaronx0607

add ui-multiselect-zh-CN.js

2021-03-04 10:39 UTC, siovene approved these changes
Thank you!

2021-03-04 13:57 UTC, siovene requested changes
Hi, could you please:

1. Revert the renaming of ui-multiselect-zh-HA to ui-multiselect-zh-hans? The jQuery localization plugin does some "magic" because it doesn't recognize "hans", so takes the first 2 letters and capitalizes them, so the request will be for zh-HA.
2. Make the same change also in the file `ui-multiselect-zh.js`? I believe it could be a fallback in some cases. 

Thanks!

2021-03-05 03:04 UTC, aaronx0607 commented
OK, I will edit the file and submit it again

2021-03-05 08:37 UTC, siovene approved these changes

2021-03-05 08:37 UTC, merged