do not allow at symbol in username
astrobin/astrobin pull request #3031
Opened 2023-05-23 19:36 UTC by sastels

https://www.notion.so/astrobindotcom/Disallow-sign-in-new-usernames-fc1f3b5c0061406b881b5965a817ee92?pvs=4

Don't allow "@" in username

Now get error:

![image](https://github.com/astrobin/astrobin/assets/8228248/dc24e3e0-1e52-4842-977e-b73dbda9de15)

2023-05-23 19:37 UTC, sastels commented on astrobin/views/registration.py
> +                _('Sorry, your username cannot contain the "@" character.')
Probably have to add this string to the i18n files? is there a tool for this?

2023-05-23 20:53 UTC, siovene commented on astrobin/views/registration.py
> +                _('Sorry, your username cannot contain the "@" character.')
You don't need to, I generate them periodically and it happens outside of the CI.

2023-05-23 21:01 UTC, siovene requested changes

2023-05-28 20:08 UTC, siovene requested changes

2023-05-28 20:08 UTC, siovene commented on astrobin/views/registration.py
> +        elif "@" in value:
You could get here if `value is None` and raise a `TypeError`. I think the cleanest way would be to check if value is None at the binning of the function, separately.

2023-06-02 01:13 UTC, sastels commented on astrobin/views/registration.py
> +        elif "@" in value:
oh, I see, there's a silent fall-through to `return None` in the original code if value is None. 👍

2023-06-02 01:16 UTC, sastels commented
Error cases now:
username is empty:
![image](https://github.com/astrobin/astrobin/assets/8228248/cbd0fb9e-0968-48f0-8fcf-f90c1d618259)

username already used:
![image](https://github.com/astrobin/astrobin/assets/8228248/7d08a62a-ace1-4bdf-9bba-75adb422db77)

username contains an "@":
![image](https://github.com/astrobin/astrobin/assets/8228248/e0d0d9b1-fd67-438b-a4df-650065b8f039)

2023-06-02 05:53 UTC, siovene approved these changes
Awesome, thnaks!

2023-06-02 05:53 UTC, merged